from typing import List, Optional, Literal

from pydantic import BaseModel, Field


class Constraints(BaseModel):
    category: Optional[str] = None
    price_min: Optional[float] = Field(default=None, ge=0)
    price_max: Optional[float] = Field(default=None, ge=0)
    color: Optional[str] = None
    size: Optional[str] = None
    brand: Optional[str] = None
    notes: Optional[str] = None


class ProductCard(BaseModel):
    product_id: str
    title: str
    brand: Optional[str] = None
    category: Optional[str] = None
    price: float
    colors: List[str] = Field(default_factory=list)
    sizes: List[str] = Field(default_factory=list)
    image_url: Optional[str] = None
    why: Optional[str] = None


class SearchRequest(BaseModel):
    query: str
    constraints: Constraints = Field(default_factory=Constraints)
    k: int = Field(default=8, ge=1, le=50)


class SearchResponse(BaseModel):
    items: List[ProductCard]


class AskRequest(BaseModel):
    query: str


class ConversationalResponse(BaseModel):
    response: str
    items: List[ProductCard]


# ============ Chrome Extension + LangGraph Models ============

class ChromeExtensionRequest(BaseModel):
    """Request from Chrome extension with search history"""
    query: str
    previousSearches: List[str] = Field(default_factory=list)
    timestamp: str


class IntentClassification(BaseModel):
    """Intent classification result from Router Agent"""
    intent_type: Literal["direct_product_search", "contextual_use_case", "off_topic"]
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    extracted_keywords: List[str] = Field(default_factory=list)
    inferred_constraints: Constraints = Field(default_factory=Constraints)


class ProductIdeas(BaseModel):
    """Product ideas generated by Creative Agent"""
    product_types: List[str] = Field(description="List of product types/categories to search for")
    search_queries: List[str] = Field(description="Optimized search queries for RAG")
    user_context: str = Field(description="Summary of user context and needs")


class AgentState(BaseModel):
    """State passed between LangGraph nodes"""
    # Input from Chrome extension
    raw_query: str
    previous_searches: List[str] = Field(default_factory=list)
    timestamp: str
    
    # Router Agent output
    intent: Optional[IntentClassification] = None
    
    # Creative Agent output (only for contextual_use_case)
    product_ideas: Optional[ProductIdeas] = None
    
    # RAG Agent output
    final_products: List[ProductCard] = Field(default_factory=list)
    
    # Final response
    response_message: str = ""
    notification_sent: bool = False
    
    class Config:
        arbitrary_types_allowed = True
